# Generated by Django 6.0 on 2025-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sports', 'Sports Nutrition'), ('weight', 'Weight Management'), ('pediatric', 'Pediatric Nutrition'), ('clinical', 'Clinical Nutrition'), ('general', 'General Nutrition')], default='general', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.CharField(max_length=300)),
                ('experience_years', models.IntegerField(default=1)),
                ('degrees', models.CharField(help_text='Comma separated e.g: MBBS, RD, PhD', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutritionists/')),
            ],
        ),
    ]
