# Generated by Django 6.0 on 2025-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='rating',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='timing',
            field=models.CharField(default=3.3),
            preserve_default=False,
        ),
    ]
