# Generated by Django 6.0 on 2025-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0002_nutritionist_rating_nutritionist_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='phone',
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='city',
            field=models.CharField(default='Lahore', help_text='e.g. Lahore, Gujrat, Islamabad', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='degrees',
            field=models.CharField(help_text='Comma separated e.g: MBBS, RD, MSc Nutrition', max_length=200),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='timing',
            field=models.CharField(help_text='e.g. 1:00 PM – 3:00 PM', max_length=50),
        ),
    ]
