# Generated by Django 6.0 on 2026-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0003_remove_nutritionist_email_remove_nutritionist_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
    ]
