# Generated by Django 6.0 on 2026-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_gender_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(default=list, help_text='Medical conditions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_food_types',
            field=models.JSONField(default=list, help_text='Allowed food categories'),
        ),
    ]
