# Generated by Django 6.0 on 2026-02-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excluded_foods',
            field=models.JSONField(default=list, help_text='List of permanently excluded food item IDs'),
        ),
    ]
