# Generated by Django 6.0 on 2026-02-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_serving', models.PositiveIntegerField(help_text='Calories per serving')),
                ('carbs_per_serving', models.FloatField(help_text='Carbohydrates (g) per serving')),
                ('proteins_per_serving', models.FloatField(help_text='Protein (g) per serving')),
                ('fats_per_serving', models.FloatField(help_text='Fat (g) per serving')),
                ('food_type', models.CharField(choices=[('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy', 'Dairy'), ('drink', 'Drink'), ('fastfood', 'Fast Food')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('lactose', 'Lactose Intolerant'), ('heart', 'Heart Disease'), ('none', 'None')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMedicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tags', to='meals.fooditem')),
                ('medical_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='meals.medicaltag')),
            ],
            options={
                'verbose_name': 'Food Medical Tag',
                'verbose_name_plural': 'Food Medical Tags',
                'unique_together': {('food', 'medical_tag')},
            },
        ),
    ]
