# Generated by Django 6.0 on 2026-02-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_userexcludedfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy', 'Dairy'), ('drink', 'Drink'), ('fastfood', 'Fast Food'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserExcludedFood',
        ),
    ]
