# Generated by Django 6.0 on 2026-02-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_fooditem_food_type_delete_userexcludedfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy', 'Dairy'), ('drink', 'Drink'), ('snack', 'Snack'), ('fastfood', 'Fast Food')], max_length=20),
        ),
    ]
