from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_fooditem_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal_suitability',
            field=models.CharField(
                choices=[
                    ('breakfast', 'Breakfast'),
                    ('lunch', 'Lunch'),
                    ('dinner', 'Dinner'),
                    ('snack', 'Snack'),
                    ('any', 'Any time'),
                ],
                db_index=True,
                default='any',
                help_text='Best meal time for this food item',
                max_length=20,
            ),
        ),
    ]# Generated by Django 6.0.3 on 2026-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_fooditem_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal_suitability',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('any', 'Any time')], db_index=True, default='any', help_text='Best meal time for this food item', max_length=20),
        ),
    ]
