# Generated by Django 6.0.3 on 2026-04-27 11:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_fooditem_meal_suitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='meal_suitability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('any', 'Any time')], db_index=True, default='any', help_text='Select all meal times that fit this food item', max_length=100),
        ),
    ]
