# Generated by Django 6.0 on 2026-01-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_gender_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate')], max_length=20)),
                ('met_value', models.FloatField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('order_number', models.PositiveSmallIntegerField()),
                ('estimated_calories', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('exercise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_exercises', to='exercises.exerciseplan')),
            ],
            options={
                'ordering': ['day_number', 'order_number'],
                'unique_together': {('exercise_plan', 'day_number', 'order_number')},
            },
        ),
    ]
