# Generated by Django 6.0 on 2026-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplanday',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
